#5 new atmosphere model
TSoGiants/TSoG_X1 pull request #19
Opened 2020-07-02 21:21 UTC by Aarush26

Created a function that calculates the temperature, pressure, and density of the atmosphere based on the input of a given altitude to address issue #5. The atmospheric model function is based off the NASA model [here](https://www.grc.nasa.gov/WWW/K-12/airplane/atmosmet.html). We are only concerned with the troposphere equations and constants, since we probably will not fly above 11,000 meters (we can dream though).

2020-07-03 18:40 UTC, TheGreatFez requested changes
Just one small change

2020-07-03 18:40 UTC, TheGreatFez commented on Simulation/AtmosphereModel.m
> +% Create input altitude
Let's remove this comment since we changed the code to a function

2020-07-03 22:12 UTC, Aarush26 reviewed
Deleted the comment that was above the function code because it referred to part of the code that was changed to make a function that used altitude as an input.

2020-07-04 03:15 UTC, TheGreatFez approved these changes
Looks great!

2020-07-04 14:42 UTC, merged